name: CI/CD

on:
   push:
      branches:
         - main
      tags:
         - "v*.*.*"

jobs:
   build-and-deploy:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v4

         - name: Set up Python 3.9
           uses: actions/setup-python@v2
           with:
              python-version: "3.9.13" # Specific version required by shinyapps.io

         - name: Install dependencies
           run: |
              python -m pip install -r requirements.txt

         - name: Install Quarto
           run: |
              wget https://quarto.org/download/latest/quarto-linux-amd64.deb
              sudo dpkg -i quarto-linux-amd64.deb

         - name: Build the app
           run: |
              quarto render index.qmd

         - name: Run the app
           run: |
              timeout 10s shiny run app.py

         - name: Configure deployment tool
           run: |
              rsconnect add \
                --account $SHINYAPPS_NAME \
                --name $SHINYAPPS_NAME \
                --token $SHINYAPPS_TOKEN \
                --secret $SHINYAPPS_SECRET
           env:
              SHINYAPPS_NAME: ${{ secrets.SHINYAPPS_NAME }}
              SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
              SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}

         - name: Deploy to Development or Production
           run: |
              if [[ "${GITHUB_REF_TYPE}" == "tag" && "${GITHUB_REF_NAME}" == "v*" ]]; then
                echo "Deploying to production app $PROD_APP_ID"
                rsconnect deploy shiny . \
                  --name "$SHINYAPPS_NAME" \
                  --app-id "$PROD_APP_ID"
              else
                echo "Deploying to development app $DEV_APP_ID"
                rsconnect deploy shiny . \
                  --name  "$SHINYAPPS_NAME" \
                  --app-id "$DEV_APP_ID" \
                  --visibility "private"
              fi
           env:
              SHINYAPPS_NAME: ${{ secrets.SHINYAPPS_NAME }}
              PROD_APP_ID: ${{ secrets.PROD_APP_ID }}
              DEV_APP_ID: ${{ secrets.DEV_APP_ID }}
