name: CI/CD

on:
   push:
      branches:
         - main
      tags:
         - "v*.*.*"

jobs:
   build and deploy:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v3

         - name: Set up Python 3.9
           uses: actions/setup-python@v2
           with:
              python-version: "3.9.13" # Specific version required by shinyapps.io

         - name: Install dependencies
           run: |
              python -m pip install -r requirements.txt

         - name: Install Quarto
           run: |
              wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.4.7/quarto-1.4.7-linux-amd64.deb
              sudo dpkg -i quarto-1.4.7-linux-amd64.deb

         - name: Build the app
           run: |
              quarto render index.qmd

         - name: Run the app
           run: |
              shiny run app.py

         - name: Configure deployment tool
           run: |
              rsconnect add \
                --account $SHINYAPPS_NAME \
                --name $SHINYAPPS_NAME \
                --token $SHINYAPPS_TOKEN \
                --secret $SHINYAPPS_SECRET
           env:
              SHINYAPPS_NAME: ${{ secrets.SHINYAPPS_NAME }}
              SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
              SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}

         - name: Deploy to Development or Production
           run: |
              if [[ "${GIT_REF}" == "refs/tags/v*" ]]; then
                echo "Deploying to production"
                rsconnect deploy shiny . -n $SHINYAPPS_NAME -a $PROD_APP_ID -V public
              else
                echo "Deploying to development"
                rsconnect deploy shiny . -n $SHINYAPPS_NAME -a $DEV_APP_ID -V private
              fi
           env:
              GIT_REF: ${{ github.ref }}
              SHINYAPPS_NAME: ${{ secrets.SHINYAPPS_NAME }}
              PROD_APP_ID: ${{ secrets.PROD_APP_ID }}
              DEV_APP_ID: ${{ secrets.DEV_APP_ID }}
